version: "3.9"

services:
  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app                     
      - static_volume:/app/staticfiles
      - ./users/migrations:/app/users/migrations 

  worker:
    build: .
    env_file: .env
    command: celery -A coffee_shop_api worker -l info
    depends_on:
      - web
      - redis
      - db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  beat:
    build: .
    env_file: .env
    command: celery -A coffee_shop_api beat -l info
    depends_on:
      - worker
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-coffee_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  


volumes:
  postgres_data:   
  static_volume: 
  grafana_data:
